apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjp7ImF1dGgiOiJkR1Z6ZEdsdVozUmxjMnhoTjBCbmJXRnBiQzVqYjIwNlpHOXdYM1l4WDJNMllUTTVOamxtTURkaE4yVmhORGRrTWpoaU9XVmpNV0l4TVdVeE5EQXlaamhsTTJGaVkyVXdaVFF5WkRVMU0yVTNNemhqT1ROaU1UQXdZekl5WldVPSJ9fX0=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deploy-service-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploy-service-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deploy-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: deploy-service-role
subjects:
- kind: ServiceAccount
  name: deploy-service-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-service
  template:
    metadata:
      labels:
        app: deploy-service
    spec:
      serviceAccountName: deploy-service-sa
      containers:
      - name: deploy-service
        image: registry.digitalocean.com/orcanet/deploy-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          value: "default"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-service
  namespace: default
spec:
  selector:
    app: deploy-service
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer