@echo off
echo Building image...
docker build -t registry.digitalocean.com/orcanet/deploy-service:latest .

echo Authenticating with DigitalOcean registry...
echo dop_v1_c6a3969f07a7ea47d28b9ec1b11e1402f8e3abce0e42d553e738c93b100c22ee | docker login registry.digitalocean.com -u testingtesla7@gmail.com --password-stdin

echo Pushing image...
docker push registry.digitalocean.com/orcanet/deploy-service:latest

echo Restarting deployment...
kubectl rollout restart deployment/deploy-service

echo Checking status...
kubectl get pods -l app=deploy-service